#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
#bspc config bottom_padding         32

# bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config click_to_focus       true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Emacs desktop='^2' state=tiled follow=on
bspc rule -a Chromium desktop='^4' follow=on
bspc rule -a Termite state=floating
bspc rule -a URxvt state=floating
bspc rule -a qterminal state=floating
