#! /bin/sh

bspc config border_width        5
bspc config window_gap         	10

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^2 focus=on
bspc rule -a Thunderbird desktop=^3 focus=on

panel &
